#!/usr/bin/env sh

set -e -u

main() {
    upgrade_system_packages
    upgrade_python_packages
}

upgrade_system_packages() {
    pkg upgrade -y
    pkg autoclean
    apt autoremove
}

upgrade_python_packages() {
    python -m pip install --requirement "${HOME}/termux-setup/requirements.txt" --upgrade --user
    python -m pip cache purge
}

main "$@"
